import { CaseStudy } from "../types";

export const CASE_STUDIES: CaseStudy[] = [
  {
    id: "power-fiber",
    title: "1. 区域电网与光纤干线铺设计划",
    category: "power",
    unit: "万元/km",
    description: "为华东区域 8 大核心电力枢纽规划特高压光纤互联拓扑，在保证全网100%连通的前提下极小化线缆铺设与土建施工总投资。",
    engineeringContext: "电力骨干网对连续性与施工成本高度敏感。通过 Kruskal / Prim 算法寻找总造价极小的连通生成子图，并配合敏感性分析评估易受地质灾害影响路段的备选冗余成本。",
    recommendedRoot: "N1",
    graph: {
      name: "华东电力枢纽特高压互联工程",
      unit: "万元/km",
      description: "8个枢纽变电站互联网络",
      nodes: [
        { id: "N1", label: "变电总站(沪)", x: 220, y: 100, type: "hub" },
        { id: "N2", label: "南京枢纽(苏)", x: 120, y: 220, type: "station" },
        { id: "N3", label: "杭州换流(浙)", x: 340, y: 150, type: "station" },
        { id: "N4", label: "合肥特高(皖)", x: 100, y: 360, type: "station" },
        { id: "N5", label: "黄山分站", x: 240, y: 320, type: "station" },
        { id: "N6", label: "宁波配电", x: 480, y: 220, type: "station" },
        { id: "N7", label: "温州末端", x: 420, y: 380, type: "client" },
        { id: "N8", label: "舟山跨海", x: 580, y: 140, type: "client" },
      ],
      edges: [
        { id: "e1", source: "N1", target: "N2", weight: 28, label: "沪苏干线" },
        { id: "e2", source: "N1", target: "N3", weight: 16, label: "沪杭骨干" },
        { id: "e3", source: "N2", target: "N3", weight: 32, label: "苏杭备用" },
        { id: "e4", source: "N2", target: "N4", weight: 14, label: "苏皖联络" },
        { id: "e5", source: "N3", target: "N5", weight: 25, label: "杭黄线" },
        { id: "e6", source: "N3", target: "N6", weight: 18, label: "杭甬线" },
        { id: "e7", source: "N4", target: "N5", weight: 20, label: "皖黄线" },
        { id: "e8", source: "N5", target: "N7", weight: 35, label: "黄温线" },
        { id: "e9", source: "N6", target: "N7", weight: 22, label: "甬温线" },
        { id: "e10", source: "N6", target: "N8", weight: 29, label: "舟山跨海缆" },
        { id: "e11", source: "N1", target: "N8", weight: 45, label: "洋山深水缆" },
        { id: "e12", source: "N4", target: "N7", weight: 52, label: "皖温远距离" },
      ],
    },
  },
  {
    id: "water-supply",
    title: "2. 城市自来水输水主管网规划",
    category: "water",
    unit: "百万元/标段",
    description: "以市政水厂与高位水库为水源点，规划连通各大居住区、工业园与商业中心的加压主输水管道，规避高压环流水锤并控制管槽开挖预算。",
    engineeringContext: "给排水系统通常构建树状支状管网以避免循环水力震荡。Prim 算法从水源主厂（W1）出发，分步向边缘片区扩散加压供水，计算最优管径投资。",
    recommendedRoot: "W1",
    graph: {
      name: "滨海新区自来水输配系统",
      unit: "百万元/标段",
      description: "水厂至各主要用水片区主干道",
      nodes: [
        { id: "W1", label: "中心水厂(总水源)", x: 380, y: 80, type: "hub" },
        { id: "W2", label: "城北净水站", x: 180, y: 160, type: "station" },
        { id: "W3", label: "东部工业园", x: 580, y: 170, type: "client" },
        { id: "W4", label: "高新科技城", x: 260, y: 280, type: "station" },
        { id: "W5", label: "中央商务区(CBD)", x: 440, y: 260, type: "station" },
        { id: "W6", label: "南部新城居住区", x: 360, y: 400, type: "client" },
        { id: "W7", label: "港口物流基地", x: 620, y: 350, type: "client" },
      ],
      edges: [
        { id: "we1", source: "W1", target: "W2", weight: 12, label: "主输管A" },
        { id: "we2", source: "W1", target: "W3", weight: 15, label: "东干管" },
        { id: "we3", source: "W1", target: "W5", weight: 11, label: "中轴管" },
        { id: "we4", source: "W2", target: "W4", weight: 9, label: "高新分支" },
        { id: "we5", source: "W3", target: "W5", weight: 16, label: "东中联络" },
        { id: "we6", source: "W3", target: "W7", weight: 14, label: "港区干管" },
        { id: "we7", source: "W4", target: "W5", weight: 8, label: "CBD联络" },
        { id: "we8", source: "W4", target: "W6", weight: 13, label: "南延管线" },
        { id: "we9", source: "W5", target: "W6", weight: 10, label: "居住区主管" },
        { id: "we10", source: "W5", target: "W7", weight: 21, label: "港区备用管" },
        { id: "we11", source: "W6", target: "W7", weight: 17, label: "南环管网" },
      ],
    },
  },
  {
    id: "pcb-routing",
    title: "3. 超大规模集成电路 (PCB) 焊盘布线",
    category: "pcb",
    unit: "mm 走线",
    description: "在芯片主板上将多组供电引脚 (VCC/GND) 与时钟总线进行最小曼哈顿/欧氏距离连通，降低寄生电容与信号延迟。",
    engineeringContext: "EDA 物理设计中常将引脚网络抽象为点集，求解最小生成树作为 Steiner 树的前置启发式骨架，降低布线拥塞度与信号损耗。",
    recommendedRoot: "P1",
    graph: {
      name: "微处理器时钟引脚总线 (Clock Pin Net)",
      unit: "mm 走线",
      description: "芯片关键引脚布线拓扑",
      nodes: [
        { id: "P1", label: "CLK_SRC (晶振源)", x: 120, y: 120, type: "hub" },
        { id: "P2", label: "ALU_CORE (运算核)", x: 280, y: 90, type: "station" },
        { id: "P3", label: "CACHE_L1 (一级缓存)", x: 200, y: 240, type: "station" },
        { id: "P4", label: "DMA_CTRL (总线控制)", x: 390, y: 190, type: "station" },
        { id: "P5", label: "DDR_PHY (内存接口)", x: 540, y: 110, type: "client" },
        { id: "P6", label: "PCIE_BRIDGE (桥接)", x: 500, y: 280, type: "client" },
        { id: "P7", label: "GPIO_PAD (外部接口)", x: 320, y: 390, type: "client" },
        { id: "P8", label: "SEC_ENCLAVE (安全核)", x: 480, y: 410, type: "client" },
      ],
      edges: [
        { id: "pe1", source: "P1", target: "P2", weight: 6.2, label: "Top-Net1" },
        { id: "pe2", source: "P1", target: "P3", weight: 4.8, label: "Clk-L1" },
        { id: "pe3", source: "P2", target: "P3", weight: 7.1, label: "Core-L1" },
        { id: "pe4", source: "P2", target: "P4", weight: 5.5, label: "Core-DMA" },
        { id: "pe5", source: "P2", target: "P5", weight: 9.3, label: "Core-DDR" },
        { id: "pe6", source: "P3", target: "P4", weight: 6.0, label: "L1-DMA" },
        { id: "pe7", source: "P3", target: "P7", weight: 5.9, label: "L1-GPIO" },
        { id: "pe8", source: "P4", target: "P5", weight: 4.2, label: "DMA-DDR" },
        { id: "pe9", source: "P4", target: "P6", weight: 5.1, label: "DMA-PCIE" },
        { id: "pe10", source: "P5", target: "P6", weight: 6.8, label: "DDR-PCIE" },
        { id: "pe11", source: "P6", target: "P8", weight: 4.5, label: "PCIE-SEC" },
        { id: "pe12", source: "P7", target: "P8", weight: 7.0, label: "GPIO-SEC" },
      ],
    },
  },
  {
    id: "mst-clustering",
    title: "4. 图论最小生成树层次聚类 (Single-Linkage)",
    category: "clustering",
    unit: "欧氏距离",
    description: "通过构建样本点完全图的最小生成树，并切断其中权重最大的 k-1 条边，实现无监督单链接层次聚类（识别任意几何形状簇群）。",
    engineeringContext: "不同于 K-Means 的凸球形限制，基于 MST 割裂的聚类能完美识别环形、流形与不规则连通团。切掉最长割边即可将数据自然分割为高内聚子群。",
    recommendedRoot: "D1",
    graph: {
      name: "客户画像多维特征分布网络",
      unit: "特征空间距离",
      description: "9 个特征样本点的全连接度量网络",
      nodes: [
        { id: "D1", label: "高净值A1", x: 140, y: 110, type: "hub", clusterId: 1 },
        { id: "D2", label: "高净值A2", x: 200, y: 150, type: "hub", clusterId: 1 },
        { id: "D3", label: "高净值A3", x: 120, y: 210, type: "hub", clusterId: 1 },
        { id: "D4", label: "大众客群B1", x: 420, y: 110, type: "station", clusterId: 2 },
        { id: "D5", label: "大众客群B2", x: 500, y: 160, type: "station", clusterId: 2 },
        { id: "D6", label: "大众客群B3", x: 450, y: 230, type: "station", clusterId: 2 },
        { id: "D7", label: "年轻长尾C1", x: 260, y: 370, type: "client", clusterId: 3 },
        { id: "D8", label: "年轻长尾C2", x: 360, y: 390, type: "client", clusterId: 3 },
        { id: "D9", label: "年轻长尾C3", x: 310, y: 440, type: "client", clusterId: 3 },
      ],
      edges: [
        { id: "ce1", source: "D1", target: "D2", weight: 1.8, label: "簇内距离" },
        { id: "ce2", source: "D2", target: "D3", weight: 2.1, label: "簇内距离" },
        { id: "ce3", source: "D1", target: "D3", weight: 2.4, label: "簇内距离" },
        { id: "ce4", source: "D4", target: "D5", weight: 2.0, label: "簇内距离" },
        { id: "ce5", source: "D5", target: "D6", weight: 1.9, label: "簇内距离" },
        { id: "ce6", source: "D4", target: "D6", weight: 2.2, label: "簇内距离" },
        { id: "ce7", source: "D7", target: "D8", weight: 2.3, label: "簇内距离" },
        { id: "ce8", source: "D8", target: "D9", weight: 1.7, label: "簇内距离" },
        { id: "ce9", source: "D7", target: "D9", weight: 2.1, label: "簇内距离" },
        { id: "ce10", source: "D2", target: "D4", weight: 8.5, label: "【簇间长边A-B】" },
        { id: "ce11", source: "D3", target: "D7", weight: 7.2, label: "【簇间长边A-C】" },
        { id: "ce12", source: "D6", target: "D8", weight: 7.8, label: "【簇间长边B-C】" },
      ],
    },
  },
  {
    id: "transit-highway",
    title: "5. 区域高速交通网络扩建工程",
    category: "traffic",
    unit: "亿元投资",
    description: "在山地、峡谷与平原并存的都市圈规划城际高快速路网，综合桥隧造价、征地补偿与地质条件，以极小资金消耗打通全域互通通行。",
    engineeringContext: "跨江大桥与穿山隧道造价极其昂贵（如 T1-T5 跨海长隧）。MST 算法识别必须修建的控制性骨干工程，并输出次优生成树以作为双向备用保通方案。",
    recommendedRoot: "T1",
    graph: {
      name: "大都市圈一小时互联交通网",
      unit: "亿元造价",
      description: "7 大节点城市快速干线规划",
      nodes: [
        { id: "T1", label: "中心首府 (T1)", x: 380, y: 110, type: "hub" },
        { id: "T2", label: "港口新区 (T2)", x: 570, y: 150, type: "station" },
        { id: "T3", label: "重工业城 (T3)", x: 200, y: 180, type: "station" },
        { id: "T4", label: "空港新城 (T4)", x: 150, y: 330, type: "client" },
        { id: "T5", label: "文化旅游岛 (T5)", x: 550, y: 340, type: "client" },
        { id: "T6", label: "物流枢纽市 (T6)", x: 350, y: 280, type: "station" },
        { id: "T7", label: "边贸南关 (T7)", x: 380, y: 440, type: "client" },
      ],
      edges: [
        { id: "te1", source: "T1", target: "T2", weight: 35, label: "东环高速" },
        { id: "te2", source: "T1", target: "T3", weight: 28, label: "西直达路" },
        { id: "te3", source: "T1", target: "T6", weight: 20, label: "中轴大道" },
        { id: "te4", source: "T2", target: "T5", weight: 42, label: "跨海特大桥" },
        { id: "te5", source: "T2", target: "T6", weight: 31, label: "港区直达" },
        { id: "te6", source: "T3", target: "T4", weight: 19, label: "临空连接线" },
        { id: "te7", source: "T3", target: "T6", weight: 25, label: "工业物流线" },
        { id: "te8", source: "T4", target: "T6", weight: 24, label: "西南环线" },
        { id: "te9", source: "T4", target: "T7", weight: 38, label: "南延通道" },
        { id: "te10", source: "T5", target: "T6", weight: 33, label: "海滨快速路" },
        { id: "te11", source: "T5", target: "T7", weight: 46, label: "东南沿海线" },
        { id: "te12", source: "T6", target: "T7", weight: 22, label: "南向大干线" },
      ],
    },
  },
  {
    id: "telecom-5g",
    title: "6. 5G/6G 通信骨干网与容灾拓扑",
    category: "telecom",
    unit: "ms 时延 / 成本",
    description: "超大规模云计算数据中心与 5G 核心机房间低时延高吞吐光网拓扑规划，兼顾生成树极小成本与网络抗毁性（Survivability）分析。",
    engineeringContext: "通信网络要求毫秒级低时延路由。MST 作为主通信拓扑时，任何单边故障都会中断通信，因此破圈法与次优生成树对设计 1+1 光保护环（Self-Healing Ring）至关重要。",
    recommendedRoot: "DC1",
    graph: {
      name: "全国超算与 5G 骨干网互联拓扑",
      unit: "ms 传输损耗权",
      description: "8 大骨干超级算力节点互联",
      nodes: [
        { id: "DC1", label: "北京主节点 (DC1)", x: 360, y: 90, type: "hub" },
        { id: "DC2", label: "乌兰察布智算 (DC2)", x: 180, y: 110, type: "station" },
        { id: "DC3", label: "上海金融云 (DC3)", x: 540, y: 200, type: "station" },
        { id: "DC4", label: "郑州中继机房 (DC4)", x: 330, y: 220, type: "station" },
        { id: "DC5", label: "成都超级算力 (DC5)", x: 140, y: 280, type: "station" },
        { id: "DC6", label: "贵安绿色数据 (DC6)", x: 220, y: 410, type: "client" },
        { id: "DC7", label: "广州湾区核心 (DC7)", x: 440, y: 390, type: "client" },
        { id: "DC8", label: "武汉汇聚分中心 (DC8)", x: 420, y: 290, type: "station" },
      ],
      edges: [
        { id: "de1", source: "DC1", target: "DC2", weight: 6, label: "京蒙超高速直连" },
        { id: "de2", source: "DC1", target: "DC3", weight: 14, label: "京沪主干波分" },
        { id: "de3", source: "DC1", target: "DC4", weight: 8, label: "京郑干线" },
        { id: "de4", source: "DC2", target: "DC5", weight: 16, label: "蒙川低时延" },
        { id: "de5", source: "DC3", target: "DC8", weight: 11, label: "沪汉沿江光网" },
        { id: "de6", source: "DC3", target: "DC7", weight: 18, label: "华东-华南直连" },
        { id: "de7", source: "DC4", target: "DC5", weight: 13, label: "郑蓉中继" },
        { id: "de8", source: "DC4", target: "DC8", weight: 7, label: "郑汉骨干" },
        { id: "de9", source: "DC5", target: "DC6", weight: 9, label: "川贵超算专网" },
        { id: "de10", source: "DC6", target: "DC7", weight: 10, label: "贵广算力出海通道" },
        { id: "de11", source: "DC7", target: "DC8", weight: 12, label: "武广高铁沿线光纤" },
      ],
    },
  },
];
